### ISSUE TITLE
color definitions as intended?

### ISSUE THREAD

**Issue by moeller0** [sqrwf/openwrt-collectd-exec-dslstats#1]
https://github.com/sqrwf/openwrt-collectd-exec-dslstats/blob/1b202bdaabb3d4b349f24aed9e7340e9bfcafe4c/www/luci-static/resources/statistics/rrdtool/definitions/exec.js#L230

Here the line and area color definitions differ (one is _regular the other is _minor), is that on purpose?

**Comment by sqrwf** [comment]
No, it should be _minor (just like the area color). I didn't notice the mistake because I don't use the line at all (noline=true), this would only show with the regular rrdtool.js. Thanks for the pointer, fixed and closed.
