### ISSUE TITLE
Duplicate color definition

### ISSUE THREAD

**Issue by moeller0** [sqrwf/openwrt-collectd-exec-dslstats#2]
https://github.com/sqrwf/openwrt-collectd-exec-dslstats/blob/1b202bdaabb3d4b349f24aed9e7340e9bfcafe4c/www/luci-static/resources/statistics/rrdtool/definitions/exec.js#L86

Two lines of:
`color:         _settings.colors.near_minor.line,`
and no area_color definition, was the second intended to be:
`area_color:         _settings.colors.near_minor.area,`

**Comment by sqrwf** [comment]
You are completely correct, thanks for the pointer, fixed.
